; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.28"

; Modules
projects[admin_menu][version] = "3.0-rc4"

projects[coder][version] = "2.2"

projects[ctools][version] = "1.4"

projects[devel][version] = "1.5"

projects[features][version] = "2.0"

projects[gmap][version] = "2.9"

projects[panels][version] = "3.4"

projects[libraries][version] = "2.2"

projects[location][version] = "3.3"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[mat_resturants][download][type] = "get"
projects[mat_resturants][download][url] = "web/profiles/standard/modules/custom/mat_resturants"
projects[mat_resturants][type] = "module"
projects[mat_resturants][version] = "1.x-1.0"

projects[module_filter][version] = "2.0-alpha2"

projects[views][version] = "3.8"

; Themes
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[mat][download][type] = "get"
projects[mat][download][url] = "web/profiles/standard/themes/mat"
projects[mat][type] = "theme"

